### ISSUE TITLE
Bookmarks get cleared on saving?

### ISSUE THREAD

**Issue by GitGet** [robcaa/numbered-bookmarks#4]
I'm running Windows.
If i create a bookmark (CTRL + SHIFT + ALT + 1), scroll though my code and jump back (CRTL + 1), everything works beautifully. Thanks for that!
But when I press CTRL + S, to save my code, (and set JSLint to work), the bookmark gets cleared.

**Comment by GitGet** [comment]
At a closer look:
I also have extension "Beautify" active and "Beautify of save" switched on.
When I deselect "Beautify on save" and activate "Beautify" manually, the bookmarks get lost. The behaviour is not related to JSLint of saving.

**Comment by robcaa** [comment]
Thanks for the detailed description from the bug.
I will check it, and fix it, one or two weeks between.

Probably the beautifier modify all lines and clear the necessary class names.

**Comment by robcaa** [comment]
OK I have a half solution: I attached a code to the onsave event. When you press CMD+S the beautifier rearrange the lines and the bookmark extension reload the bookmarks. But there is a problem. The beautifier extension rearrange lines (create new lines, delete empty lines, etc) and the bookmarked line pointing the original line. It does not take the rearranged lines. So the whole bookmarked lines slide.

In addition, the manual beatufy does not load the bookmarks. To make this work somehow you should get the beautifier extension event, if ever there is one.

Probably more than this we can not do. :(

If it's good you, I will upload the changes and closes this issue. Otherwise, I look forward to your suggestions.

**Comment by GitGet** [comment]
That certainly sounds promising to me!
It makes perfect sense that bookmarks may shift when beautify adds / drops / splits or joins lines. Without communication between Beautify and Numbered Bookmarks, the bookmarks cannot be adjusted, I understand that! Do you think an interface to negotiatate changes in the bookmarks (line numbers) could be implemented in future? ;-) Should I knock on their door as well?

Anyway, at this point having bookmarks that take me back to the vincinity of the line that I planned to end up in would be a whole lot better then seeing my all my bookmarks gone every time. So please do push the update?

Thanks for all the effort!

**Comment by robcaa** [comment]
Ok I updated the code. 
If it is possible to work together with the beautifier extension, than I will be develop the code.
